repos:

    - repo: 'https://github.com/codespell-project/codespell'
      rev: v2.4.1
      hooks:
        - id: codespell
          args:
            - '--skip="./.*,*.csv,*.json,*.pyc,./docs/_build/*,./htmlcov/*"'
            - '--quiet-level=2'
          exclude_types:
            - csv
            - json
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.5
      hooks:
        # Run the linter.
        - id: ruff
          args: [ --fix ]
        # Run the formatter.
        - id: ruff-format
    - repo: 'https://github.com/pre-commit/pre-commit-hooks'
      rev: v4.5.0
      hooks:
        - id: check-docstring-first
        - id: check-shebang-scripts-are-executable
        - id: check-toml
        - id: check-yaml
          args: [--unsafe]
        - id: end-of-file-fixer
        - id: fix-byte-order-marker
        - id: mixed-line-ending
        - id: trailing-whitespace
